### ISSUE TITLE
Vagueness: "The Flag should be Respected"

### ISSUE THREAD

**Issue by lacedemonian** [TheAmeliaMay/AmericanValues#4]
It's possible to believe so without believing in either legislative or social consequences for disrespecting the flag, which is the actual issue here. The question is also a bit leading in that answering "disagree" implies the user does not respect the flag, which is not necessarily true, the user may just believe flag respect is not worthy of social or legal enforcement. I would be more specific about what you mean by this question. "People who disrespect the flag deserve some social consequences" or "some legal consequences" depending on how you want this question to align the user.

**Comment by TheAmeliaMay** [comment]
The cultural axis is supposed to measure your views on American society, not just what legislation you support — although there's significant overlap. This is because two people may support the same policies, yet vote against each other, because one candidate resonated with them more culturally.

That being said, maybe I should focus on legislation and leave out everything else? Regardless, I should probably reword the question to make more sense.
