### ISSUE TITLE
Request for additional option: Object to the question.

### ISSUE THREAD

**Issue by HydraheadHunter** [TheAmeliaMay/AmericanValues#6]
I'm very, very left; and having gone through the quiz, there were several points where you propose a question that I had to take a neutral/unsure stance on it because the question was phrased in a way that made an assumption I fundementally disagree with agree with.

For example, the trans military question ("Should trans people be allowed to serve in the US military" [cc]): I don't think anyone should be allowed to serve in the US military because I believe the US military shouldn't exist; but, I can't say mark 'disagree' because that strongly implies I agree with prejudice and discrimination against trans folks; A thing I'm definitely very against.

So, I'm suggesting a sixth option: "Object," which is different from "Neutral," in that it gives you the chance to provide feedback.

**Comment by TheAmeliaMay** [comment]
Thanks for your post!

I know that a lot of the questions are built upon certain assumptions people might disagree with, but due to the nature of the quiz itself: you have to suspend that disagreement in order to choose the best option, not the ideal option. If this was a multiple-choice quiz: I would definitely have an option reading something similar to "We shouldn't have a military at all."

If you answer "Neutral": your score will not be affected, which is why there's no "Object" or "Skip" option: they would have the same function. But in your case: I'd suggest suspending your disagreement temporarily in order to answer the _best_ option, not the ideal one.

I quite like the idea to provide feedback on each question, but I'm unsure how to actually implement that at the moment. I'll look into it, though. Thanks!
